In [2]:
import torch
import math

In [3]:
math.ceil(3.3 / 0.2)

17

In [9]:
ref_y, ref_x = torch.meshgrid(torch.linspace(-3.3, 3.3, 34),torch.linspace(-3.3, 3.3 , 34))

print(ref_y.shape)
print(ref_x.shape)

flow_coord = torch.stack((ref_y, ref_x), dim=-1)

print(flow_coord.shape)

torch.Size([34, 34])
torch.Size([34, 34])
torch.Size([34, 34, 2])


In [10]:
print(flow_coord[0,0])
print(flow_coord[0,-1])
print(flow_coord[-1,0])
print(flow_coord[-1,-1])

tensor([-3.3000, -3.3000])
tensor([-3.3000,  3.3000])
tensor([ 3.3000, -3.3000])
tensor([3.3000, 3.3000])
